"""Initial migration

Revision ID: c10eade748c2
Revises: 
Create Date: 2024-08-17 19:24:25.167730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c10eade748c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_molecules_smiles', 'molecules', ['smiles'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_molecules_smiles', 'molecules', type_='unique')
    # ### end Alembic commands ###
