"""empty message

Revision ID: 2b445446c699
Revises: 891bd932318b
Create Date: 2024-09-05 12:58:44.532866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b445446c699"
down_revision: Union[str, None] = "891bd932318b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("molecules_mass_idx", table_name="molecules")
    op.drop_index(
        "pg_trgm_on_name_idx", table_name="molecules", postgresql_using="gist"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "pg_trgm_on_name_idx",
        "molecules",
        ["name"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("molecules_mass_idx", "molecules", ["mass"], unique=False)
    # ### end Alembic commands ###
