"""empty message

Revision ID: 824e978716d2
Revises: 299a5ba28cf4
Create Date: 2024-09-05 15:13:23.755144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "824e978716d2"
down_revision: Union[str, None] = "299a5ba28cf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "drug_molecule_molecule_id_fkey", "drug_molecule", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "drug_molecule",
        "molecules",
        ["molecule_id"],
        ["molecule_id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "drug_molecule", type_="foreignkey")
    op.create_foreign_key(
        "drug_molecule_molecule_id_fkey",
        "drug_molecule",
        "molecules",
        ["molecule_id"],
        ["molecule_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
