"""molecule mass

Revision ID: ade9092f3941
Revises: 72ab7eb68212
Create Date: 2024-09-01 21:40:18.928986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade9092f3941'
down_revision: Union[str, None] = '72ab7eb68212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molecules', sa.Column('mass', sa.Float(), nullable=False))
    op.alter_column('molecules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('molecules', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('molecules', 'mass')
    # ### end Alembic commands ###
