name: Docker Image CI and Testing with Pytest

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
          pip install -r src/requirements.txt
          pip install flake8

    - name: Run Pytest
      run: pytest

    - name: Run Flake8
      run: flake8 .

    - name: Build the Docker image
      run: docker build --file src/Dockerfile --tag my-fastapi-app src/
